name: Deploy-Flask-to-EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Flask to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: theamanshakya/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: /home/ubuntu/flask-app  # Update the path based on your project structure

      - name: Verify or Create Target Directory
        run: ssh -i ${{ secrets.EC2_SSH_KEY }} ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }} "mkdir -p /home/ubuntu/flask-app"

      - name: Install Python and Dependencies
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Debug Information
        run: |
           whoami
           id
           ls -al /home
           ls -al /home/ubuntu

      - name: Install Flask Dependencies
        run: |
          cd /home/ubuntu/flask-app
          pip install -r requirements.txt

      - name: Restart Flask Application
        uses: theamanshakya/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            pkill -f "flask --app run.py run" || true  # Stop any existing Flask process if running
            nohup flask --app run.py run --host=0.0.0.0 > /dev/null 2>&1 &
