name: Deploy-Flask-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Flask to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: /home/ubuntu/flask-app  # Adjust the path based on your project structure

      - name: Install Python and Dependencies
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Flask Dependencies
        run: |
          cd /home/server
          pip install -r requirements.txt

      - name: Restart Flask Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            pkill -f "flask --app run.py run"  # Stop any existing Flask process
            nohup flask --app run.py run --host=0.0.0.0 > /dev/null 2>&1 &
